# Generated by Django 2.1.3 on 2018-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('creator_name', models.CharField(max_length=50)),
                ('creator_email', models.CharField(max_length=100)),
            ],
        ),
    ]
