# Generated by Django 2.1.3 on 2018-11-12 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181112_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 15, 16, 10, 512317)),
        ),
    ]
